const db = require('../config/db');

/**
 * Status code → { label, progress }
 */
const STATUS_MAP = {
 
  1:  { label: 'Unassigned',                 progress: 0 },   
  2:  { label: 'Assigned',                   progress: 20 },   
  3:  { label: 'Following',                  progress: 30 },
  4:  { label: 'Approved',                   progress: 50 },
  5:  { label: 'Reject',                     progress: 0 },    
  6:  { label: 'CIBIL Check',                progress: 30 },
  7:  { label: 'CIBIL Rejected',             progress: 0 },    
  22: { label: 'No Response',                progress: 0 },    
  24: { label: 'Not Exist/Out of Service',   progress: 10 },


  10: { label: 'New Lead',                   progress: 0 },
  11: { label: 'Assigned',                   progress: 50 },   
  12: { label: 'Doc Collection',             progress: 60 },
  13: { label: 'File Login',                 progress: 70 },
  14: { label: 'File Login Rejected',        progress: 0 },    
  15: { label: 'Sanction',                   progress: 80 },
  16: { label: 'Sanction Rejected',          progress: 0 },    
  17: { label: 'Disbursement',               progress: 100 },  
  18: { label: 'Completed',                  progress: 100 },
  23: { label: 'Doc Collection Rejected',    progress: 0 },    
};


const getLeadsByConnector = async (connectorId) => {
  const query = `
    SELECT 
      lp.id,
      lp.firstname,
      lp.lastname,
      lp.email,
      lp.mobilenumber,
      lp.loantype,
      lp.loanamount,
      lp.status AS lead_status,
      lp.createdon,
      lt.id AS track_id,
      lt.status AS track_status,
      lt.notes AS track_notes,
      lt.customername,
      lt.tracknumber,
      lt.modifyon AS track_modified,
      lt.disbursementamount,
      lt.payoutpercent
    FROM leadpersonaldetails lp
    LEFT JOIN leadtrackdetails lt ON lt.leadid = lp.id
    WHERE lp.connectorid = $1
    ORDER BY lp.createdon DESC
  `;
  const { rows } = await db.query(query, [connectorId]);
  return rows;
};

/**
 * Get full lead detail by lead ID (personal + track + loan info).
 */
const getLeadById = async (leadId) => {
  const query = `
    SELECT 
      lp.*,
      lt.id AS track_id,
      lt.status AS track_status,
      lt.notes AS track_notes,
      lt.tracknumber,
      lt.customername,
      lt.loantype AS track_loantype,
      lt.desireloanamount,
      lt.tenure,
      lt.preferedbank,
      lt.cibilscore,
      lt.bankname,
      lt.applicationnumber,
      lt.logindate,
      lt.loginvalue,
      lt.sanctionvalue,
      lt.sanctiondate,
      lt.disbursementamount,
      lt.modifyon AS track_modified,
      lt.contactfollowedby,
      lt.isnoresponse
    FROM leadpersonaldetails lp
    LEFT JOIN leadtrackdetails lt ON lt.leadid = lp.id
    WHERE lp.id = $1
  `;
  const { rows } = await db.query(query, [leadId]);
  return rows[0] || null;
};

/**
 * Assign a lead: insert into leadtrackdetails with status=2.
 * Also updates leadpersonaldetails.status to 2.
 */
const assignLead = async ({ leadId, contactFollowedBy, organizationId, notes, customerName }) => {
  const client = await db.pool.connect();
  try {
    await client.query('BEGIN');

    // Idempotent: check if track record already exists
    const existing = await client.query(
      'SELECT id, tracknumber FROM leadtrackdetails WHERE leadid = $1 LIMIT 1', [leadId]
    );

    let trackRecord;

    if (existing.rows.length > 0) {
      // Update existing track record
      const { rows } = await client.query(
        `UPDATE leadtrackdetails 
         SET status = 2, notes = $1, customername = $2, contactfollowedby = $3, 
             organizationid = $4, modifyon = NOW()
         WHERE leadid = $5
         RETURNING id, leadid, status, tracknumber`,
        [notes || 'Assigned', customerName || '', contactFollowedBy, organizationId || 1001, leadId]
      );
      trackRecord = rows[0];
    } else {
      // Insert new track record (tracknumber is auto-generated by Postgres)
      const insertQuery = `
        INSERT INTO leadtrackdetails (
          leadid, status, notes, customername,
          contactfollowedby, organizationid, modifyon,
          isdirectmeet, occupationtype, loantype, desireloanamount,
          tenure, preferedbank, cibilscore, incometype, incomeamount,
          isidproof, isageproof, isaddessproof, iscreditcardstatement,
          isexistingloantrack, iscurrentaccountstatement, isstabilityproof,
          isbankstatement, ispayslip, isform16, isbusinessproof,
          isitr, isgststatement, isencumbrancecertificate, istitledeed,
          isparentdeed, islayoutplan, isregulationorder, isbuildingpermit,
          ispropertytax, ispatta, isconstructionagreement, issaleagreement,
          isapf, isudsregistration, isrcbook, bankname, applicationnumber,
          loginvalue, sanctionroi, sanctionvalue, psdcondition,
          islegal, istechnical, legalreport, technicalreport,
          ispsdconditionverified, leadfollowedby, isnoresponse,
          payoutpercent, ispaid, connectorcontactid, disbursementamount,
          datastrength, compname, compcat, custsegment, customer
        )
        VALUES (
          $1, 2, $2, $3,
          $4, $5, NOW(),
          false, '', '', '0',
          0, '', 0, '', '0',
          false, false, false, false,
          false, false, false,
          false, false, false, false,
          false, false, false, false,
          false, false, false, false,
          false, false, false, false,
          false, false, false, '', '',
          '0', '0', '0', '',
          false, false, '', '',
          false, 0, false,
          '0', false, 0, '0',
          '', '', '', '', false
        )
        RETURNING id, leadid, status, tracknumber
      `;
      const values = [leadId, notes || 'Assigned', customerName || '', contactFollowedBy, organizationId || 1001];
      const { rows } = await client.query(insertQuery, values);
      trackRecord = rows[0];
    }

    // Update leadpersonaldetails status to 2 (Assigned)
    await client.query('UPDATE leadpersonaldetails SET status = 2 WHERE id = $1', [leadId]);

    await client.query('COMMIT');
    return trackRecord;
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('assignLead transaction failed:', err.message);
    throw err;
  } finally {
    client.release();
  }
};


/**
 * Update the status of a tracked lead.
 * Also logs a history entry in leadtrackhistorydetails.
 */
const updateLeadStatus = async ({ trackId, leadId, newStatus, notes, userId }) => {
  // Update leadtrackdetails
  await db.query(
    'UPDATE leadtrackdetails SET status = $1, notes = $2, modifyon = NOW() WHERE id = $3',
    [newStatus, notes || '', trackId]
  );

  // Update leadpersonaldetails.status
  await db.query(
    'UPDATE leadpersonaldetails SET status = $1 WHERE id = $2',
    [newStatus, leadId]
  );

  // Insert history record
  await db.query(
    `INSERT INTO leadtrackhistorydetails 
      (tracknumber, leadid, status, notes, isdirectmeet, createon, contactfollowedby, leadfollowedby)
     SELECT tracknumber, leadid, $1, $2, false, NOW(), contactfollowedby, leadfollowedby
     FROM leadtrackdetails WHERE id = $3`,
    [newStatus, notes || '', trackId]
  );

  return { trackId, leadId, newStatus };
};

/**
 * Get tracking history for a lead.
 */
const getLeadTrackHistory = async (leadId) => {
  const query = `
    SELECT id, tracknumber, leadid, status, notes, createon, contactfollowedby
    FROM leadtrackhistorydetails
    WHERE leadid = $1
    ORDER BY createon DESC
  `;
  const { rows } = await db.query(query, [leadId]);
  return rows;
};

module.exports = {
  STATUS_MAP,
  getLeadsByConnector,
  getLeadById,
  assignLead,
  updateLeadStatus,
  getLeadTrackHistory,
};
