// ─────────────────────────────────────────────
// Design Tokens — Semantic meaning of UI elements
// ─────────────────────────────────────────────
export const tokens = {
    colors: {
        background: 'background',
        surface: 'surface',
        surfaceElevated: 'surfaceElevated',
        primary: 'primary',
        primaryGradStart: 'primaryGradStart',
        primaryGradEnd: 'primaryGradEnd',
        border: 'border',
        inputBg: 'inputBg',
        textPrimary: 'textPrimary',
        textSecondary: 'textSecondary',
        textDisabled: 'textDisabled',
        textLink: 'textLink',
        textInverse: 'textInverse',
        success: 'success',
        successBg: 'successBg',
        warning: 'warning',
        warningBg: 'warningBg',
        error: 'error',
        errorBg: 'errorBg',
        info: 'info',
        infoBg: 'infoBg',
        cyan: 'cyan',
        cyanBg: 'cyanBg',
        overlay: 'overlay',
        shadow: 'shadow',
    },
    spacing: {
        xxs: 2, xs: 4, sm: 8, md: 12, base: 16,
        lg: 20, xl: 24, xxl: 32, xxxl: 48, huge: 64,
    },
    radius: {
        none: 0, xs: 4, sm: 6, md: 8, lg: 12,
        xl: 16, xxl: 24, full: 9999,
    },
    typography: {
        fontRegular: 'System',
        fontMedium: 'System',
        fontSemiBold: 'System',
        fontBold: 'System',
        display: 28, h1: 22, h2: 18, h3: 16,
        bodyLg: 15, body: 14, bodySm: 13,
        label: 12, caption: 11,
        amount: 24, amountSm: 16,
    },
};
